import { useCallback, useEffect, useMemo, useRef, useState, type DragEvent } from "react"
import { Calendar, CheckCircle2, CloudUpload, Download, Eye, FileImage, FileX, LoaderCircle, Search, Trash2, X, XCircle } from "lucide-react"
import type { ListResponse, OcrRecognitionRecord, OcrRecognitionStatus } from "@zform/shared"
import { api } from "@/apis/framework-api"
import { formatDate } from "@/components/status-pill"
import { Alert, Badge, Button, Card, CardContent, ConfirmDialog, Dialog, EmptyState, IconButton, Input, PageHeader, Pagination, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tabs } from "@/components/ui"

const EMPTY_HISTORY: ListResponse<OcrRecognitionRecord> = { items: [], total: 0, page: 1, pageSize: 20, pageCount: 1 }
const STATUS_LABELS: Record<OcrRecognitionStatus, string> = { RECOGNIZING: "识别中", SUCCESS: "识别成功", FAILED: "识别失败" }
const ACCEPTED_TYPES = ["image/jpeg", "image/png", "image/webp"] as const

interface UploadItem { localId: string; file: File; previewUrl: string; status: OcrRecognitionStatus; record?: OcrRecognitionRecord; error?: string }

function OcrStatusBadge({ status }: { status: OcrRecognitionStatus }) { return <Badge variant={status === "SUCCESS" ? "success" : status === "FAILED" ? "danger" : "warning"}>{status === "RECOGNIZING" && <LoaderCircle className="spin" />}{status === "SUCCESS" && <CheckCircle2 />}{status === "FAILED" && <XCircle />}{STATUS_LABELS[status]}</Badge> }
function ResultFields({ record }: { record: OcrRecognitionRecord }) { const fields = [["平台", record.platform], ["订单号", record.orderNo], ["商品名称", record.productName], ["支付金额", record.amount], ["支付时间", record.paymentTime], ["支付状态", record.paymentStatus], ["支付方式", record.paymentMethod], ["收款方", record.receiver]]; return <dl className="ocr-result-fields">{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "—"}</dd></div>)}</dl> }
function downloadBase64(base64: string, filename: string) { const bytes = Uint8Array.from(atob(base64), (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url) }
async function fileBase64(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = () => reject(reader.error || new Error("读取图片失败")); reader.readAsDataURL(file) }) }

export function OcrRecognition() {
  const [tab, setTab] = useState("upload")
  const [historyRevision, setHistoryRevision] = useState(0)
  return <><PageHeader eyebrow="智能工具 / OCR" title="支付截图识别" description="批量上传支付截图，AI 自动提取平台、订单、金额、时间和收款信息。" />
    <Tabs className="ocr-tabs" value={tab} onChange={setTab} items={[{ id: "upload", label: "上传识别" }, { id: "history", label: "历史记录" }]} />
    {tab === "upload" ? <OcrUpload onChanged={() => setHistoryRevision((value) => value + 1)} onOpenHistory={() => setTab("history")} /> : <OcrHistory revision={historyRevision} />}
  </>
}

function OcrUpload({ onChanged, onOpenHistory }: { onChanged: () => void; onOpenHistory: () => void }) {
  const inputRef = useRef<HTMLInputElement>(null)
  const itemsRef = useRef<UploadItem[]>([])
  const [items, setItems] = useState<UploadItem[]>([])
  const [dragging, setDragging] = useState(false)
  const [detail, setDetail] = useState<UploadItem | null>(null)
  const [deleting, setDeleting] = useState<UploadItem | null>(null)
  const [message, setMessage] = useState<{ variant: "success" | "danger"; text: string } | null>(null)
  useEffect(() => { itemsRef.current = items }, [items])
  useEffect(() => () => { itemsRef.current.forEach((item) => URL.revokeObjectURL(item.previewUrl)) }, [])
  const patchItem = useCallback((localId: string, patch: Partial<UploadItem>) => setItems((current) => current.map((item) => item.localId === localId ? { ...item, ...patch } : item)), [])
  const processFile = useCallback(async (file: File) => {
    const localId = crypto.randomUUID(); const previewUrl = URL.createObjectURL(file)
    setItems((current) => [{ localId, file, previewUrl, status: "RECOGNIZING" }, ...current])
    try { const result = await api.recognizeOcr({ filename: file.name, mimeType: file.type as typeof ACCEPTED_TYPES[number], base64Data: await fileBase64(file) }); patchItem(localId, { status: result.record.status, record: result.record, ...(result.record.errorMessage ? { error: result.record.errorMessage } : {}) }); setMessage({ variant: result.success ? "success" : "danger", text: result.success ? `${file.name} 识别成功。` : `${file.name}：${result.record.errorMessage || "识别失败"}` }); onChanged() }
    catch (reason) { patchItem(localId, { status: "FAILED", error: reason instanceof Error ? reason.message : "处理失败" }); setMessage({ variant: "danger", text: reason instanceof Error ? reason.message : "处理失败" }) }
  }, [onChanged, patchItem])
  const handleFiles = (files: FileList | File[]) => { const accepted = [...files].filter((file) => ACCEPTED_TYPES.includes(file.type as typeof ACCEPTED_TYPES[number]) && file.size <= 8 * 1024 * 1024); if (!accepted.length) { setMessage({ variant: "danger", text: "请选择不超过 8MB 的 JPG、PNG 或 WebP 图片。" }); return } accepted.forEach((file) => void processFile(file)) }
  const drop = (event: DragEvent) => { event.preventDefault(); setDragging(false); handleFiles(event.dataTransfer.files) }
  const remove = async () => { if (!deleting) return; try { if (deleting.record) await api.removeOcrRecognition(deleting.record.id); URL.revokeObjectURL(deleting.previewUrl); setItems((current) => current.filter((item) => item.localId !== deleting.localId)); setDeleting(null); onChanged() } catch (reason) { setDeleting(null); setMessage({ variant: "danger", text: reason instanceof Error ? reason.message : "删除失败" }) } }
  const exportItems = async () => { const ids = items.flatMap((item) => item.record?.status === "SUCCESS" ? [item.record.id] : []); if (!ids.length) return; try { const result = await api.exportOcrRecognitions({ ids }); downloadBase64(result.base64, result.filename); setMessage({ variant: "success", text: `已导出 ${result.count} 条识别结果。` }) } catch (reason) { setMessage({ variant: "danger", text: reason instanceof Error ? reason.message : "导出失败" }) } }
  const successCount = items.filter((item) => item.status === "SUCCESS").length
  return <><div className="ocr-upload-actions">{items.length > 0 && <><Button onClick={onOpenHistory}><FileImage />查看历史</Button><Button disabled={!successCount} onClick={() => void exportItems()}><Download />导出本次结果 ({successCount})</Button></>}</div>{message && <Alert variant={message.variant} className="ocr-alert">{message.text}</Alert>}
    <Card className={`ocr-drop-zone${dragging ? " active" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={drop} onClick={() => inputRef.current?.click()}><CardContent><input ref={inputRef} hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => { if (event.target.files) handleFiles(event.target.files); event.target.value = "" }} /><div className="ocr-upload-icon"><CloudUpload /></div><strong>{dragging ? "松开即可上传" : "拖拽或点击上传截图"}</strong><p>支持 JPG、PNG、WebP，可批量上传；单张图片最大 8MB</p><div>{["淘宝", "京东", "拼多多", "美团", "支付宝", "微信支付"].map((platform) => <Badge key={platform}>{platform}</Badge>)}</div></CardContent></Card>
    {items.length > 0 && <section className="ocr-upload-list"><header><strong>本次上传 · {items.length} 张</strong><span>{items.filter((item) => item.status === "RECOGNIZING").length ? "AI 正在识别，请稍候…" : "处理完成"}</span></header>{items.map((item) => <Card className="ocr-upload-item" key={item.localId}><img src={item.previewUrl} alt={item.file.name} /><div><header><strong><FileImage />{item.file.name}</strong><OcrStatusBadge status={item.status} /></header>{item.record?.status === "SUCCESS" ? <div className="ocr-upload-summary"><span>{item.record.platform || "未知平台"}</span><strong>{item.record.amount || "未识别金额"}</strong><span>{item.record.orderNo || item.record.productName || "未识别订单信息"}</span></div> : <p>{item.status === "RECOGNIZING" ? "正在提取支付信息…" : item.error || "识别失败"}</p>}</div><div className="ocr-item-actions">{item.record?.status === "SUCCESS" && <IconButton aria-label="查看详情" onClick={() => setDetail(item)}><Eye /></IconButton>}<IconButton aria-label="删除" onClick={() => setDeleting(item)}><Trash2 /></IconButton></div></Card>)}</section>}
    <Dialog open={Boolean(detail)} title="识别详情" width={780} onClose={() => setDetail(null)}>{detail?.record && <div className="ocr-detail"><div><span>原始截图</span><img src={detail.previewUrl} alt={detail.file.name} /></div><div><span>识别结果</span><ResultFields record={detail.record} /></div></div>}</Dialog>
    <ConfirmDialog open={Boolean(deleting)} title="删除识别记录" description={`确认删除“${deleting?.file.name || ""}”及其识别结果？`} destructive confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => void remove()} />
  </>
}

function OcrHistory({ revision }: { revision: number }) {
  const [keyword, setKeyword] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [page, setPage] = useState(1); const [data, setData] = useState(EMPTY_HISTORY); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selected, setSelected] = useState<string[]>([]); const [detail, setDetail] = useState<OcrRecognitionRecord | null>(null); const [imageUrl, setImageUrl] = useState<string | null>(null); const [deleting, setDeleting] = useState<OcrRecognitionRecord | null>(null)
  const query = useMemo(() => ({ ...(keyword ? { keyword } : {}), ...(startDate ? { startDate } : {}), ...(endDate ? { endDate } : {}), page, pageSize: 20 }), [endDate, keyword, page, startDate])
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await api.ocrRecognitions(query)); setSelected([]) } catch (reason) { setError(reason instanceof Error ? reason.message : "加载失败") } finally { setLoading(false) } }, [query])
  useEffect(() => { void load() }, [load, revision])
  useEffect(() => { if (!detail) { setImageUrl((current) => { if (current) URL.revokeObjectURL(current); return null }); return } let active = true; void api.ocrImage(detail.id).then((blob) => { if (active) setImageUrl(URL.createObjectURL(blob)) }).catch((reason) => setError(reason instanceof Error ? reason.message : "图片加载失败")); return () => { active = false } }, [detail])
  const remove = async () => { if (!deleting) return; try { await api.removeOcrRecognition(deleting.id); setDeleting(null); await load() } catch (reason) { setDeleting(null); setError(reason instanceof Error ? reason.message : "删除失败") } }
  const exportRows = async () => { try { const result = await api.exportOcrRecognitions({ ...(selected.length ? { ids: selected } : {}), ...(startDate ? { startDate } : {}), ...(endDate ? { endDate } : {}) }); downloadBase64(result.base64, result.filename) } catch (reason) { setError(reason instanceof Error ? reason.message : "导出失败") } }
  return <><Card className="ocr-history"><div className="ocr-history-toolbar"><div className="management-search"><Search /><Input value={keyword} onChange={(event) => { setKeyword(event.target.value); setPage(1) }} placeholder="搜索订单号、商品、平台或收款方" /></div><Calendar /><Input type="date" value={startDate} onChange={(event) => { setStartDate(event.target.value); setPage(1) }} /><span>至</span><Input type="date" value={endDate} onChange={(event) => { setEndDate(event.target.value); setPage(1) }} /><Button onClick={() => { setKeyword(""); setStartDate(""); setEndDate(""); setPage(1) }}><X />清除</Button><Button variant="primary" onClick={() => void exportRows()}><Download />{selected.length ? `导出已选 (${selected.length})` : "导出 Excel"}</Button></div>{error && <Alert variant="danger" className="ocr-alert">{error}</Alert>}<CardContent>{loading ? <EmptyState icon={<LoaderCircle className="spin" />} title="正在加载识别记录…" /> : !data.items.length ? <EmptyState icon={<FileX />} title="暂无识别记录" description="上传支付截图后，结果会保存在这里" /> : <Table><TableHeader><TableRow><TableHead><input type="checkbox" checked={selected.length === data.items.length} onChange={(event) => setSelected(event.target.checked ? data.items.map((record) => record.id) : [])} /></TableHead><TableHead>平台</TableHead><TableHead>订单号</TableHead><TableHead>商品名称</TableHead><TableHead>支付金额</TableHead><TableHead>支付时间</TableHead><TableHead>识别状态</TableHead><TableHead>上传时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{data.items.map((record) => <TableRow key={record.id}><TableCell><input type="checkbox" checked={selected.includes(record.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, record.id] : current.filter((id) => id !== record.id))} /></TableCell><TableCell><Badge>{record.platform || "—"}</Badge></TableCell><TableCell><code>{record.orderNo || "—"}</code></TableCell><TableCell>{record.productName || "—"}</TableCell><TableCell><strong>{record.amount || "—"}</strong></TableCell><TableCell>{record.paymentTime || "—"}</TableCell><TableCell><OcrStatusBadge status={record.status} /></TableCell><TableCell>{formatDate(record.createdAt, true)}</TableCell><TableCell><div className="management-actions"><IconButton aria-label="查看详情" onClick={() => setDetail(record)}><Eye /></IconButton><IconButton aria-label="删除" onClick={() => setDeleting(record)}><Trash2 /></IconButton></div></TableCell></TableRow>)}</TableBody></Table>}</CardContent><Pagination page={data.page} pageCount={data.pageCount} total={data.total} pageSize={data.pageSize} onPageChange={setPage} /></Card>
    <Dialog open={Boolean(detail)} title="识别详情" description={detail?.originalFilename} width={780} onClose={() => setDetail(null)}>{detail && <div className="ocr-detail"><div><span>原始截图</span>{imageUrl ? <img src={imageUrl} alt={detail.originalFilename} /> : <div className="ocr-image-loading"><LoaderCircle className="spin" /></div>}</div><div><span>识别结果</span><ResultFields record={detail} />{detail.errorMessage && <Alert variant="danger">{detail.errorMessage}</Alert>}</div></div>}</Dialog>
    <ConfirmDialog open={Boolean(deleting)} title="删除识别记录" description={`确认删除“${deleting?.originalFilename || ""}”？此操作不可撤销。`} destructive confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => void remove()} />
  </>
}
