import { useMemo, useState } from "react"
import { Edit3, GripVertical, MenuSquare, Plus, Search, Trash2 } from "lucide-react"
import type { SystemMenuRecord } from "@zform/shared"
import { api } from "@/apis/framework-api"
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Checkbox, ConfirmDialog, Dialog, EmptyState, FormField, Input, Select, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui"

interface Props { menus: SystemMenuRecord[]; onChanged: () => Promise<void>; onError: (message: string | null) => void }
interface MenuDraft extends SystemMenuRecord { editing?: boolean }
const targetLabels: Record<SystemMenuRecord["target"], string> = { dashboard: "工作台", "document-list": "单据列表", settings: "用户设置", help: "帮助页", "menu-management": "菜单管理", "department-management": "部门管理", "user-management": "用户管理", "role-management": "角色管理", "declaration-name": "报关名称", "ocr-recognition": "支付截图识别" }
const emptyMenu = (): MenuDraft => ({ id: "", groupId: "system", groupLabel: "系统管理", label: "", icon: "FileText", target: "help", order: 100, enabled: true })

export function MenuManagement({ menus, onChanged, onError }: Props) {
  const [keyword, setKeyword] = useState("")
  const [draft, setDraft] = useState<MenuDraft | null>(null)
  const [deleting, setDeleting] = useState<SystemMenuRecord | null>(null)
  const [draggingId, setDraggingId] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const filtered = useMemo(() => menus.filter((menu) => !keyword.trim() || `${menu.label} ${menu.id} ${menu.groupLabel} ${menu.permissionCode || ""}`.toLowerCase().includes(keyword.trim().toLowerCase())), [keyword, menus])
  const save = async () => { if (!draft) return; setSaving(true); onError(null); const { editing, ...input } = draft; void editing; try { if (draft.editing) { const { id, ...update } = input; await api.updateMenu(id, update) } else await api.createMenu(input); setDraft(null); await onChanged() } catch (reason) { onError(reason instanceof Error ? reason.message : "保存菜单失败") } finally { setSaving(false) } }
  const remove = async () => { if (!deleting) return; setSaving(true); onError(null); try { await api.removeMenu(deleting.id); setDeleting(null); await onChanged() } catch (reason) { setDeleting(null); onError(reason instanceof Error ? reason.message : "删除菜单失败") } finally { setSaving(false) } }
  const reorder = async (sourceId: string, targetId: string) => { const source = menus.find((menu) => menu.id === sourceId); const target = menus.find((menu) => menu.id === targetId); if (!source || !target || source.id === target.id) return; onError(null); const { id: sourceKey, ...sourceInput } = source; const { id: targetKey, ...targetInput } = target; try { await Promise.all([api.updateMenu(sourceKey, { ...sourceInput, order: target.order }), api.updateMenu(targetKey, { ...targetInput, order: source.order })]); await onChanged() } catch (reason) { onError(reason instanceof Error ? reason.message : "菜单排序失败") } }

  return <><Card className="management-table"><CardHeader><div><CardTitle>菜单列表 <Badge>{filtered.length}</Badge></CardTitle><p>拖动行可交换显示顺序，保存后应用外壳立即刷新。</p></div><div className="management-toolbar"><div className="management-search"><Search /><Input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="搜索菜单、分组或权限码" /></div><Button variant="primary" onClick={() => setDraft(emptyMenu())}><Plus />新建菜单</Button></div></CardHeader><CardContent>
    {!filtered.length ? <EmptyState icon={<MenuSquare />} title="暂无菜单" /> : <Table><TableHeader><TableRow><TableHead /><TableHead>分组 / 菜单</TableHead><TableHead>图标</TableHead><TableHead>跳转目标</TableHead><TableHead>权限码</TableHead><TableHead>排序</TableHead><TableHead>状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((menu) => <TableRow key={menu.id} draggable onDragStart={() => setDraggingId(menu.id)} onDragEnd={() => setDraggingId(null)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggingId) void reorder(draggingId, menu.id); setDraggingId(null) }} className={draggingId === menu.id ? "dragging" : ""}><TableCell><GripVertical className="drag-handle" /></TableCell><TableCell><strong>{menu.groupLabel} / {menu.label}</strong><small>{menu.id}</small></TableCell><TableCell><code>{menu.icon}</code></TableCell><TableCell>{targetLabels[menu.target]}{menu.targetId && <small>{menu.targetId}</small>}</TableCell><TableCell><code>{menu.permissionCode || "公开"}</code></TableCell><TableCell>{menu.order}</TableCell><TableCell><Badge variant={menu.enabled ? "success" : "neutral"}>{menu.enabled ? "显示" : "隐藏"}</Badge></TableCell><TableCell><div className="management-actions"><Button size="sm" variant="ghost" onClick={() => setDraft({ ...menu, editing: true })}><Edit3 />编辑</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(menu)}><Trash2 />删除</Button></div></TableCell></TableRow>)}</TableBody></Table>}
  </CardContent></Card>
  <Dialog open={Boolean(draft)} title={draft?.editing ? "编辑菜单" : "新建菜单"} description="菜单目标必须映射到框架已有工作区页面。" width={760} onClose={() => setDraft(null)} footer={<><Button onClick={() => setDraft(null)}>取消</Button><Button variant="primary" loading={saving} disabled={!draft?.id.trim() || !draft?.label.trim()} onClick={() => void save()}>{draft?.editing ? "保存" : "创建"}</Button></>}>{draft && <div className="management-form"><FormField label="菜单标识" required><Input value={draft.id} disabled={draft.editing} onChange={(event) => setDraft({ ...draft, id: event.target.value })} placeholder="system:example" /></FormField><FormField label="菜单名称" required><Input value={draft.label} onChange={(event) => setDraft({ ...draft, label: event.target.value })} /></FormField><FormField label="分组标识" required><Input value={draft.groupId} onChange={(event) => setDraft({ ...draft, groupId: event.target.value })} /></FormField><FormField label="分组名称" required><Input value={draft.groupLabel} onChange={(event) => setDraft({ ...draft, groupLabel: event.target.value })} /></FormField><FormField label="图标名称"><Input value={draft.icon} onChange={(event) => setDraft({ ...draft, icon: event.target.value })} /></FormField><FormField label="跳转目标"><Select value={draft.target} onChange={(event) => setDraft({ ...draft, target: event.target.value as SystemMenuRecord["target"] })}>{Object.entries(targetLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></FormField><FormField label="目标参数"><Input value={draft.targetId || ""} onChange={(event) => setDraft({ ...draft, targetId: event.target.value || undefined })} placeholder="单据类型等页面参数" /></FormField><FormField label="所需权限"><Input value={draft.permissionCode || ""} onChange={(event) => setDraft({ ...draft, permissionCode: event.target.value || undefined })} placeholder="留空表示公开" /></FormField><FormField label="排序号"><Input type="number" value={draft.order} onChange={(event) => setDraft({ ...draft, order: Number(event.target.value) || 0 })} /></FormField><label className="ui-inline-check"><Checkbox checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} />显示菜单</label></div>}</Dialog>
  <ConfirmDialog open={Boolean(deleting)} title="确认删除菜单" description={`确认删除“${deleting?.label || ""}”？应用外壳会立即移除此入口。`} destructive confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => void remove()} />
  </>
}
