import { useMemo, useState } from "react"
import { Edit3, Plus, Search, Trash2, Users } from "lucide-react"
import type { DepartmentRecord, RoleRecord, UserRecord, UserStatus } from "@zform/shared"
import { api } from "@/apis/framework-api"
import { formatDate } from "@/components/status-pill"
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Checkbox, ConfirmDialog, Dialog, EmptyState, FormField, Input, Select, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui"

interface Props { users: UserRecord[]; roles: RoleRecord[]; departments: DepartmentRecord[]; onChanged: () => Promise<void>; onError: (message: string | null) => void }
interface UserDraft { id: string; editing: boolean; name: string; email: string; departmentId: string; status: UserStatus; roleIds: string[] }
const emptyUser = (): UserDraft => ({ id: "", editing: false, name: "", email: "", departmentId: "", status: "ACTIVE", roleIds: [] })

export function UserManagement({ users, roles, departments, onChanged, onError }: Props) {
  const [keyword, setKeyword] = useState("")
  const [status, setStatus] = useState<"ALL" | UserStatus>("ALL")
  const [draft, setDraft] = useState<UserDraft | null>(null)
  const [deleting, setDeleting] = useState<UserRecord | null>(null)
  const [saving, setSaving] = useState(false)
  const filtered = useMemo(() => users.filter((user) => (status === "ALL" || user.status === status) && (!keyword.trim() || `${user.id} ${user.name} ${user.email || ""} ${user.departmentName || ""}`.toLowerCase().includes(keyword.trim().toLowerCase()))), [keyword, status, users])
  const edit = (user: UserRecord) => setDraft({ id: user.id, editing: true, name: user.name, email: user.email || "", departmentId: user.departmentId || "", status: user.status, roleIds: user.roles.map((role) => role.id) })
  const save = async () => { if (!draft) return; setSaving(true); onError(null); const input = { name: draft.name, ...(draft.email ? { email: draft.email } : {}), ...(draft.departmentId ? { departmentId: draft.departmentId } : {}), status: draft.status, roleIds: draft.roleIds }; try { if (draft.editing) await api.updateUser(draft.id, input); else await api.createUser({ id: draft.id, ...input }); setDraft(null); await onChanged() } catch (reason) { onError(reason instanceof Error ? reason.message : "保存用户失败") } finally { setSaving(false) } }
  const remove = async () => { if (!deleting) return; setSaving(true); onError(null); try { await api.removeUser(deleting.id); setDeleting(null); await onChanged() } catch (reason) { setDeleting(null); onError(reason instanceof Error ? reason.message : "删除用户失败") } finally { setSaving(false) } }

  return <><Card className="management-table"><CardHeader><div><CardTitle>用户列表 <Badge>{filtered.length}</Badge></CardTitle><p>禁用用户会保留历史关系，但不再获得角色权限。</p></div><div className="management-toolbar"><div className="management-search"><Search /><Input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="搜索用户、邮箱或部门" /></div><Select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="ALL">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></Select><Button variant="primary" onClick={() => setDraft(emptyUser())}><Plus />新建用户</Button></div></CardHeader><CardContent>
    {!filtered.length ? <EmptyState icon={<Users />} title="暂无符合条件的用户" /> : <Table><TableHeader><TableRow><TableHead>用户标识</TableHead><TableHead>姓名</TableHead><TableHead>邮箱</TableHead><TableHead>部门</TableHead><TableHead>角色</TableHead><TableHead>状态</TableHead><TableHead>创建时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((user) => <TableRow key={user.id}><TableCell><code>{user.id}</code></TableCell><TableCell><strong>{user.name}</strong></TableCell><TableCell>{user.email || "—"}</TableCell><TableCell>{user.departmentName || "—"}</TableCell><TableCell><div className="permission-tags">{user.roles.map((role) => <Badge key={role.id} variant="primary">{role.name}</Badge>)}{!user.roles.length && "—"}</div></TableCell><TableCell><Badge variant={user.status === "ACTIVE" ? "success" : "neutral"}>{user.status === "ACTIVE" ? "启用" : "停用"}</Badge></TableCell><TableCell>{formatDate(user.createdAt, true)}</TableCell><TableCell><div className="management-actions"><Button size="sm" variant="ghost" onClick={() => edit(user)}><Edit3 />编辑</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(user)}><Trash2 />删除</Button></div></TableCell></TableRow>)}</TableBody></Table>}
  </CardContent></Card>
  <Dialog open={Boolean(draft)} title={draft?.editing ? "编辑用户" : "新建用户"} description="用户通过部门和角色进入统一权限体系。" width={720} onClose={() => setDraft(null)} footer={<><Button onClick={() => setDraft(null)}>取消</Button><Button variant="primary" loading={saving} disabled={!draft?.id.trim() || !draft?.name.trim()} onClick={() => void save()}>{draft?.editing ? "保存" : "创建"}</Button></>}>{draft && <div className="management-form"><FormField label="用户标识" required><Input value={draft.id} disabled={draft.editing} onChange={(event) => setDraft({ ...draft, id: event.target.value })} placeholder="登录主体唯一标识" /></FormField><FormField label="姓名" required><Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></FormField><FormField label="邮箱"><Input type="email" value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })} /></FormField><FormField label="状态"><Select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as UserStatus })}><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></Select></FormField><FormField label="所属部门" className="span-2"><Select value={draft.departmentId} onChange={(event) => setDraft({ ...draft, departmentId: event.target.value })}><option value="">未分配部门</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}（{department.code}）</option>)}</Select></FormField><FormField label="分配角色" className="span-2"><div className="role-options">{roles.map((role) => <label className={draft.roleIds.includes(role.id) ? "selected" : ""} key={role.id}><Checkbox checked={draft.roleIds.includes(role.id)} onChange={(event) => setDraft({ ...draft, roleIds: event.target.checked ? [...draft.roleIds, role.id] : draft.roleIds.filter((id) => id !== role.id) })} /><span>{role.name}<small>{role.code}</small></span></label>)}</div></FormField></div>}</Dialog>
  <ConfirmDialog open={Boolean(deleting)} title="确认删除用户" description={`确认删除“${deleting?.name || ""}”？通常建议停用用户以保留审计关系。`} destructive confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => void remove()} />
  </>
}
