import { useState } from "react"
import { Bell, Plus, Search } from "lucide-react"
import { Alert, Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Checkbox, ColumnSettings, Dialog, EmptyState, FormField, IconButton, Input, PageHeader, Pagination, Progress, Select, Separator, Spinner, TabPanel, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tabs, Textarea } from "./index"

export function UiShowcase() {
  const [dialogOpen, setDialogOpen] = useState(false)
  const [tab, setTab] = useState("basic")
  const [page, setPage] = useState(1)
  const [showcaseColumns, setShowcaseColumns] = useState(["name", "usage", "status"])
  return <><PageHeader eyebrow="Framework / Components" title="共通组件" description="业务页面应优先组合这些基础组件，再通过 Schema 和插件扩展行为。" actions={<><ColumnSettings columns={[{ id: "name", label: "组件" }, { id: "usage", label: "用途" }, { id: "status", label: "状态" }]} visibleColumnIds={showcaseColumns} onChange={(ids) => { if (ids.length) setShowcaseColumns(ids) }} onReset={() => setShowcaseColumns(["name", "usage", "status"])} /><Button variant="primary" onClick={() => setDialogOpen(true)}><Plus />打开对话框</Button></>} /><div className="ui-showcase-grid">
    <Card><CardHeader><div><CardTitle>按钮与状态</CardTitle><CardDescription>统一颜色、尺寸、加载和禁用状态</CardDescription></div></CardHeader><CardContent className="ui-showcase-row"><Button variant="primary">主要操作</Button><Button>次要操作</Button><Button variant="success">成功操作</Button><Button variant="danger">危险操作</Button><Button variant="ghost">文字操作</Button><IconButton aria-label="通知"><Bell /></IconButton><Button loading>处理中</Button></CardContent></Card>
    <Card><CardHeader><div><CardTitle>徽标与反馈</CardTitle><CardDescription>用于状态、校验和操作结果</CardDescription></div></CardHeader><CardContent><div className="ui-showcase-row"><Badge>默认</Badge><Badge variant="primary">处理中</Badge><Badge variant="success">已完成</Badge><Badge variant="warning">待审批</Badge><Badge variant="danger">异常</Badge><Spinner label="加载数据" /></div><Separator /><Progress value={64} label="示例进度" /><Alert title="提示" variant="info">组件不包含业务状态，业务含义由调用方提供。</Alert></CardContent></Card>
    <Card><CardHeader><div><CardTitle>表单字段</CardTitle><CardDescription>原生语义、统一焦点和错误反馈</CardDescription></div></CardHeader><CardContent className="ui-form-demo"><FormField htmlFor="demo-name" label="名称" required hint="请输入可识别的名称"><Input id="demo-name" placeholder="输入名称" /></FormField><FormField htmlFor="demo-type" label="类型"><Select id="demo-type" defaultValue="document"><option value="document">单据</option><option value="report">报表</option></Select></FormField><FormField htmlFor="demo-note" label="说明" error="示例错误信息"><Textarea id="demo-note" placeholder="输入说明" /></FormField><label className="ui-inline-check"><Checkbox defaultChecked />启用此配置</label></CardContent></Card>
    <Card><CardHeader><div><CardTitle>标签与空状态</CardTitle><CardDescription>受控标签页适合页面内局部切换</CardDescription></div></CardHeader><CardContent><Tabs value={tab} onChange={setTab} items={[{ id: "basic", label: "基础信息" }, { id: "history", label: "操作记录" }]} /><TabPanel active={tab === "basic"}><EmptyState icon={<Search />} title="暂无配置" description="创建第一项配置后将在这里展示" action={<Button size="sm">立即创建</Button>} /></TabPanel><TabPanel active={tab === "history"}><EmptyState title="暂无操作记录" /></TabPanel></CardContent></Card>
    <Card className="ui-showcase-wide"><CardHeader><div><CardTitle>表格与分页</CardTitle><CardDescription>简单数据展示使用语义表格，复杂单据列表继续使用统一查询列表</CardDescription></div></CardHeader><Table><TableHeader><TableRow><TableHead>组件</TableHead><TableHead>用途</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Button</TableCell><TableCell>统一操作入口</TableCell><TableCell><Badge variant="success">稳定</Badge></TableCell></TableRow><TableRow><TableCell>Dialog</TableCell><TableCell>模态交互</TableCell><TableCell><Badge variant="success">稳定</Badge></TableCell></TableRow></TableBody></Table><Pagination page={page} pageCount={3} pageSize={20} total={45} onPageChange={setPage} /></Card>
  </div><Dialog open={dialogOpen} title="共通对话框" description="支持遮罩关闭和 Escape 键关闭" onClose={() => setDialogOpen(false)} footer={<><Button onClick={() => setDialogOpen(false)}>取消</Button><Button variant="primary" onClick={() => setDialogOpen(false)}>确认</Button></>}><p className="ui-confirm-description">后续业务对话框复用此容器，只提供内容与操作，不要重复实现遮罩、层级和键盘关闭。</p></Dialog></>
}
